/* Run against a local preview. PLAYWRIGHT_MODULE may point to a bundled runtime. */
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const base = process.env.PORTFOLIO_URL || 'http://127.0.0.1:4173';
const projects = require('../data/projects.json');
(async () => {
  const browser = await chromium.launch({ headless: true, channel: process.env.BROWSER_CHANNEL || 'chrome' });
  const errors = [];
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(base, { waitUntil: 'networkidle' });
  assert.equal(await page.locator('.project-card').count(), projects.length);
  assert.equal(await page.locator('.project-card:visible').count(), 6);
  await page.getByRole('button', { name: /View all projects/ }).click();
  assert.equal(await page.locator('.project-card:visible').count(), projects.length);
  assert.match(page.url(), /view=all/);
  for (const cat of ['Games','Platforms','Commerce','People & Culture','Tools','Immersive']) {
    await page.locator(`[data-filter="${cat}"]`).click();
    assert.equal(await page.locator('.project-card:visible').count(), projects.filter(p => p.category === cat).length, cat);
  }
  await page.locator('[data-filter="All"]').click();
  await page.getByRole('searchbox').fill('myanmar fonts');
  assert.equal(await page.locator('.project-card:visible').count(), 2);
  assert.match((await page.locator('.project-card:visible h3').allTextContents()).join(' '), /Glyph/);
  await page.reload({ waitUntil: 'networkidle' });
  assert.equal(await page.getByRole('searchbox').inputValue(), 'myanmar fonts');
  assert.equal(await page.locator('.project-card:visible').count(), 2);
  await page.getByRole('searchbox').fill('no-such-voyage');
  assert.equal(await page.locator('.project-card:visible').count(), 0);
  assert.equal(await page.locator('.empty-state').isVisible(), true);
  await page.locator('#reset-search').click();
  assert.equal(await page.locator('.project-card:visible').count(), 6);
  assert.equal(await page.getByRole('searchbox').inputValue(), '');
  await page.locator('h1').click();
  await page.keyboard.press('/');
  assert.equal(await page.getByRole('searchbox').evaluate(el => el === document.activeElement), true);
  await page.locator('.motion-toggle').click();
  assert.equal(await page.locator('html').evaluate(el => el.classList.contains('motion-paused')), true);
  await page.reload({ waitUntil: 'networkidle' });
  assert.equal(await page.locator('.motion-toggle').getAttribute('aria-pressed'), 'false', 'Decorative motion resets on a fresh page');
  await page.locator('[data-set-filter="Commerce"]').click();
  assert.equal(await page.locator('.project-card:visible').count(), projects.filter(p => p.category === 'Commerce').length);

  const axeSource = process.env.AXE_SOURCE;
  const accessibility = [];
  async function audit(p, label) {
    if (!axeSource) return;
    await p.addScriptTag({ path: axeSource });
    const result = await p.evaluate(async () => await axe.run(document, { runOnly: { type: 'tag', values: ['wcag2a', 'wcag2aa', 'wcag21aa'] } }));
    accessibility.push({ label, violations: result.violations.map(v => ({ id: v.id, impact: v.impact, description: v.description, nodes: v.nodes.map(n => ({target:n.target,summary:n.failureSummary})).slice(0,8) })) });
  }
  await page.goto(base+'/?view=all', {waitUntil:'networkidle'});
  await audit(page, 'Desktop home, all projects');
  await page.locator('[data-art="bounty"]').click();
  assert.equal(await page.locator('.hero-bounty').isVisible(), true);
  assert.equal(await page.locator('.hero-ship').isVisible(), false);
  await page.locator('[data-art="ship"]').click();
  assert.equal(await page.locator('.hero-ship').isVisible(), true);
  assert.equal(await page.locator('.hero-bounty').isVisible(), false);
  await page.locator('[data-resume]:visible').first().click();
  await page.locator('.resume-paper').waitFor();
  assert.equal(await page.locator('.resume-dialog').isVisible(), true);
  assert.equal(await page.locator('.resume-dialog .resume-entry').count(), 32);
  await audit(page, 'Resume popup');
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('[data-resume]:visible').first().evaluate(el => el === document.activeElement), true);
  const commercePreview = page.locator('.project-cover[data-preview-title="BurmaMart"]');
  await commercePreview.click();
  assert.equal(await page.getByRole('dialog').isVisible(), true);
  assert.equal(await page.locator('#preview-title').innerText(), 'BurmaMart');
  await page.locator('#preview-image').evaluate(img => img.decode());
  await audit(page, 'Desktop screenshot viewer');
  await page.locator('.preview-zoom').click();
  assert.equal(await page.locator('.preview-zoom').getAttribute('aria-pressed'), 'true');
  assert.equal(await page.locator('.preview-viewport').evaluate(el => el.scrollWidth > el.clientWidth), true);
  await page.keyboard.press('Escape');
  assert.equal(await page.getByRole('dialog').isVisible(), false);
  assert.equal(await commercePreview.evaluate(el => el === document.activeElement), true);
  await page.locator('.personal-disclosure>summary').click();
  assert.equal(await page.locator('.personal-card').count(), 5);
  assert.equal(await page.locator('.personal-links a').count(), 10);
  assert.equal(await page.locator('[data-personal-step="-1"]').isDisabled(), true);
  await page.locator('[data-personal-step="1"]').click();
  await page.waitForFunction(() => document.querySelector('.personal-track').scrollLeft > 100);
  await page.locator('.personal-track').focus();
  await page.keyboard.press('ArrowLeft');
  await page.waitForFunction(() => document.querySelector('.personal-track').scrollLeft < 2);
  assert.equal(await page.locator('.tech-chip').count(), 33);
  assert.equal(await page.locator('.tech-chip[target="_blank"]').count(), 3);
  const unmatchedTech = await page.locator('[data-tech]').evaluateAll(chips => chips.filter(chip => !Array.from(document.querySelectorAll('.project-card')).some(card => chip.dataset.tech.toLowerCase().split(/\s+/).every(term => card.dataset.search.includes(term)))).map(chip => chip.dataset.tech));
  assert.deepEqual(unmatchedTech, [], 'Every project-search tile has matching work');
  for (const summary of await page.locator('.skill>summary').all()) await summary.click();
  await page.locator('#skills').scrollIntoViewIfNeeded();
  await page.locator('.tech-chip img').evaluateAll(imgs => Promise.all(imgs.map(img => img.decode())));
  assert.equal(await page.locator('.tech-chip img').evaluateAll(imgs => imgs.every(img => img.complete && img.naturalWidth > 0)), true);
  assert.equal(await page.locator('.tech-chip').first().evaluate(el => getComputedStyle(el).display), 'flex');
  await page.locator('[data-tech="Next.js"]').click();
  assert.equal(await page.getByRole('searchbox').inputValue(), 'Next.js');
  assert.ok(await page.locator('.project-card:visible').count() > 0);
  assert.equal(new URL(page.url()).hash, '#projects');
  await page.getByRole('searchbox').fill('');
  await page.locator('.gear-toggle').click();
  assert.equal(await page.locator('html').evaluate(el => el.classList.contains('gear-five')), true);
  await page.reload({waitUntil:'networkidle'});
  assert.equal(await page.locator('.gear-toggle').getAttribute('aria-pressed'), 'true');
  await page.locator('.gear-toggle').click();
  assert.equal(await page.locator('html').evaluate(el => el.classList.contains('gear-five')), false);
  for (const tab of await page.getByRole('tab').all()) {
    await tab.click();
    const panel = page.getByRole('tabpanel');
    assert.equal(await panel.count(), 1);
    assert.equal(await tab.getAttribute('aria-selected'), 'true');
    assert.ok(await panel.locator('a[href*="github.com/"]').count() >= 1);
    assert.equal(await panel.getByRole('link', {name:/Launch experience/}).count(), 1);
  }
  await page.getByRole('tab').last().press('ArrowRight');
  assert.equal(await page.getByRole('tab').first().getAttribute('aria-selected'), 'true');
  await page.getByRole('tab').first().press('End');
  assert.equal(await page.getByRole('tab').last().getAttribute('aria-selected'), 'true');
  await page.getByRole('tab').last().press('Home');
  await page.locator('[data-world-step="1"]').first().click();
  assert.equal(await page.locator('#world-position').innerText(), '02 / 06');
  await page.locator('[data-world-step="-1"]').first().click();
  assert.equal(await page.locator('#world-position').innerText(), '01 / 06');
  await page.locator('.captain-memory summary').click();
  assert.equal(await page.locator('.captain-memory').getAttribute('open'), '');
  await page.locator('.captain-memory summary').click();
  for (const theme of ['dark','light']) {
    if (theme === 'light') await page.locator('.day-toggle').click();
    assert.equal(await page.locator('html').getAttribute('data-theme'), theme);
    await page.reload({waitUntil:'networkidle'});
    assert.equal(await page.locator('html').getAttribute('data-theme'), theme);
    for (const layout of ['cards','list']) {
      await page.locator(`[data-layout="${layout}"]`).click();
      assert.equal(await page.locator(`[data-layout="${layout}"]`).getAttribute('aria-pressed'), 'true');
      for (const width of [320,375,390,650,768,1024,1440,2560]) {
        await page.setViewportSize({width,height:width===650?375:900});
        assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth + 1), false, `${theme} ${layout} overflow at ${width}`);
      }
      await audit(page, `${theme} theme, ${layout} layout`);
    }
  }
  await page.reload({waitUntil:'networkidle'});
  assert.equal(await page.locator('.project-grid').evaluate(el=>el.classList.contains('manifest')),true);
  await page.locator('[data-layout="cards"]').click();
  await page.locator('.day-toggle').click();
  await page.setViewportSize({width:390,height:844});
  await page.locator('.menu-toggle').click();
  assert.equal(await page.locator('.main-nav').isVisible(), true);
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('.menu-toggle').getAttribute('aria-expanded'), 'false');
  assert.equal(await page.locator('.main-nav').isVisible(), false);
  await page.locator('.menu-toggle').click();
  await page.locator('.main-nav a[href$="#about"]').click();
  assert.equal(await page.locator('.main-nav').isVisible(), false);
  await audit(page, 'Mobile home');
  if (!await page.locator('.personal-disclosure').evaluate(el=>el.open)) await page.locator('.personal-disclosure>summary').click();
  await page.locator('.personal-preview').first().click();
  await audit(page, 'Mobile screenshot viewer');
  await page.locator('.preview-zoom').click();
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth + 1), false, 'Viewer contains enlarged image on mobile');
  await page.locator('.preview-viewport').evaluate(el => el.scrollLeft = 200);
  assert.ok(await page.locator('.preview-viewport').evaluate(el => el.scrollLeft) > 0);
  await page.getByRole('button', {name:'Close preview'}).click();
  await page.waitForFunction(() => !document.documentElement.classList.contains('preview-open'));
  assert.equal(await page.locator('html').evaluate(el => el.classList.contains('preview-open')), false);

  for (const project of projects) {
    const response = await page.goto(base+'/projects/'+project.id+'/', {waitUntil:'domcontentloaded'});
    assert.equal(response.status(),200,project.id);
    assert.equal(await page.locator('h1').innerText(),project.title);
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth + 1),false,project.id+' mobile overflow');
    await page.setViewportSize({width:320,height:740});
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth + 1),false,project.id+' narrow mobile overflow');
    await page.setViewportSize({width:390,height:844});
  }
  await page.goto(base+'/projects/som-bi/', {waitUntil:'networkidle'});
  await audit(page,'SOM BI case study');
  assert.equal(await page.locator('a[href*="som.mlbb"]').count(),0);
  await page.goto(base+'/resume/',{waitUntil:'networkidle'});
  assert.equal(await page.locator('#print-resume').isVisible(),true);
  await audit(page,'Résumé');
  await page.emulateMedia({media:'print'});
  assert.equal(await page.locator('body').evaluate(el=>getComputedStyle(el).color),'rgb(0, 0, 0)');
  assert.equal(await page.locator('body').evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(255, 255, 255)');
  await page.emulateMedia({media:'screen'});

  await page.goto(base+'/showcase/', {waitUntil:'networkidle'});
  await audit(page, 'Gallery, dark theme');
  await page.locator('.day-toggle').click();
  await audit(page, 'Gallery, light theme');

  const touch = await browser.newPage({isMobile:true,hasTouch:true,viewport:{width:390,height:844}});
  await touch.goto(base,{waitUntil:'networkidle'});
  await touch.locator('.world-stage').scrollIntoViewIfNeeded();
  const bounds = await touch.locator('.world-scene:visible').boundingBox();
  const cdp = await touch.context().newCDPSession(touch);
  const start = {x:bounds.x + bounds.width - 35,y:bounds.y + 80};
  await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[start]});
  for(let dx=25;dx<=200;dx+=25) await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:start.x-dx,y:start.y}]});
  await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
  assert.equal(await touch.locator('#world-position').innerText(), '02 / 06', 'Touch swipe advances scene');
  await touch.close();

  const noJS = await browser.newPage({javaScriptEnabled:false,viewport:{width:390,height:844}});
  await noJS.goto(base,{waitUntil:'networkidle'});
  assert.equal(await noJS.locator('.project-card:visible').count(),projects.length);
  assert.equal(await noJS.locator('.main-nav').isVisible(),true);
  assert.equal(await noJS.evaluate(() => document.documentElement.scrollWidth > innerWidth + 1),false);
  const reduce = await browser.newPage({reducedMotion:'reduce'});
  await reduce.goto(base,{waitUntil:'networkidle'});
  assert.equal(await reduce.locator('html').evaluate(el => el.classList.contains('motion-paused')),true);
  assert.equal(await reduce.locator('.hero-ship').evaluate(el=>getComputedStyle(el).animationName),'none');
  assert.deepEqual(errors,[]);
  if (accessibility.length) console.log(JSON.stringify(accessibility,null,2));
  console.log('PASS: filters, technology search/icons, artwork switch, personal collection controls, touch swipe, showcase tabs/arrows/source links, URL state, keyboard controls, mobile menu, theme/Gear 5/layout persistence, page motion controls, all case routes, eight widths in both themes/layouts, no-JS fallback, and reduced motion.');
  await browser.close();
  if(accessibility.some(x=>x.violations.length)) process.exitCode=1;
})().catch(error=>{console.error(error);process.exit(1);});
